== Version History

[cols=",,",options="header",]
|===
|*Version* |*Date (y/m/d)*|*Changes*
|0.9.1 |2023/4/7 |Uppdates to sync with reference code and message detailsfor ratification
|===

== TODO

. Re-order, cleanup and make one PDF (`RISC-V N-Trace Encoder Specification`)
. Expand on MSEO/MDO
. Remove duplicated parts

== Overview and key assumptions

[arabic]
. This document provides analysis and qualification of Nexus trace messages and potential applicability for RISC-V trace.
. This document is based on following Nexus specification (called *_Nexus spec_* later on):

http://nexus5001.org/wp-content/uploads/2018/05/IEEE-ISTO-5001-2012-v3.0.1-Nexus-Standard.pdf

[arabic, start=3]
. Terminology compatible with *_Nexus spec_* will be used.
. It is not required that the reader is familiar with *_Nexus spec_* itself, but in case of doubt it is suggested to read it as things are well explained there.
.. Certain details of the *_Nexus spec_* may not be applicable to RISC-V, so be careful.
. Some sections of this document may directly refer to appropriate parts of *_Nexus spec_*. This will be done as follows *_Nexus spec [SECTION 6]._*

== Original Nexus Messages - Classification

. *_Nexus spec [Table 4-5—Nexus Public Messages]_* shows list of all nexus messages.
. Here is this table with added extra column detailing relevance of trace messages for RISC-V:

[cols=",,,",]
|===
|*Message Name *                                   |*TCODE* |*Direction* |*RISC-V Trace Applicability*
|Debug Status                                      |0       |From target |Not used (debug)
|Device ID                                         |1       |From target |Not used (debug)
|Ownership Trace                                   |2       |From target |`Level 1.2` (for RTOS/OS context)
|Program Trace - Direct Branch                     |3       |From target |`Level 1` (basic set)
|Program Trace - Indirect Branch                   |4       |From target |`Level 1` (basic set)
|Data Trace - Data Write                           |5       |From target |`Level 4` (data trace)
|Data Trace - Data Read                            |6       |From target |`Level 4` (data trace)
|Data Acquisition                                  |7       |From target |`Level 3` (instrumentation trace)
|Error                                             |8       |From target |`Level 1` (basic set)
|Program Trace - Synchronization                   |9       |From target |`Level 1` (basic set)
|Program Trace - Correction                        |10      |From target |`Level 1.1` (cancelling)
|Program Trace - Direct Branch with Sync           |11      |From target |`Level 1` (basic set)
|Program Trace - Indirect Branch with Sync         |12      |From target |`Level 1` (basic set)
|Data Trace - Data Write with Sync                 |13      |From target |`Level 4` (data trace)
|Data Trace - Data Read with Sync                  |14      |From target |`Level 4` (data trace)
|Watchpoint Hit                                    |15      |From target |Not used (debug)
|Reserved                                          |16 - 19 |--          |Reserved
|Port Replacement - Output                         |20      |From target |Not applicable
|Port Replacement - Input                          |21      |From tool   |Not applicable
|Auxiliary Access - Read                           |22      |Both ways   |Not used (debug)
|Auxiliary Access - Write                          |23      |Both ways   |Not used (debug)
|Auxiliary Access - Read Next                      |24      |Both ways   |Not used (debug)
|Auxiliary Access - Write Next                     |25      |Both ways   |Not used (debug)
|Auxiliary Access - Response                       |26      |Both ways   |Not used (debug)
|Program Trace - Resource Full                     |27      |From target |`Level 1.1` (overflow handling)
|Program Trace - Indirect Branch History           |28      |From target |`Level 2.1` (better compression)
|Program Trace - Indirect Branch History with Sync |29      |From target |`Level 2.1` (better compression)
|Program Trace - Repeat Branch                     |30      |From target |`Level 2.2` (loop compression)
|Program Trace - Repeat Instruction                |31      |From target |Not applicable
|Program Trace - Repeat Instruction with Sync      |32      |From target |Not applicable
|Program Trace - Correlation                       |33      |From target |`Level 4` (correlate data trace)
|In - Circuit Trace                                |34      |From target |`Level 5` (bus trace)
|In - Circuit Trace with Sync                      |35      |From target |`Level 5` (bus trace)
|Reserved                                          |36-55   |--          |Reserved
|Vendor - Defined Message                          |56-62   |Both ways   |Reserved
|Vendor - Defined Extension Message                |63      |Both ways   |Reserved
|===

Explanation of levels (color coded)

* `Level 1` Provides basic PC trace (may be even more trimmed for primitive trace).
* `Level 2` Provides more compressed PC trace (2 options).
* `Level 3` Instrumentation trace (substitute for full data trace).
* `Level 4` Data trace (addresses and values of transfers can be traced).
* `Level 5` Adds trace of buses in the system (advanced topic for future).

Short explanation of all Level1 .. Level5 messages (*_Nexus spec_* provides a lot of details):

* Ownership Trace (*TCODE=2*) - used to track context switching (when OS/RTOS changes task).
* Program Trace - Direct/Indirect Branch (*TCODE=3, 4*) - simplest form of program trace.
* Data Trace - … (*TCODE=5, 6*) - data trace (addresses and values).
* Data Acquisition (*TCODE=7*) - can be used for instrumentation trace (for different purposes).
* Error (*TCODE=8*) - reports different overrun error conditions.
* Program Trace - … (*TCODE=9, 11, 12*) - different forms of program trace synchronization.
* Program Trace - Resource Full (*TCODE=27*) - handlign overflows of internal counters.
* Program Trace - Indirect Branch History … (*TCODE=28, 29*) - better compression of branches.
* Program Trace - Repeat Branch (*TCODE=30*) - allows compression of loops.
* Program Trace - Correlation (*TCODE=33*) - correlate trace flow with data trace or the end.

== Nexus MSEO/MDO

[arabic]
. When RISC-V Nexus Trace exists with other Nexus implementation on the system MSEO/MDO must be common.
[arabic]
.. SRC field should be defined for RISC-V
. Nexus messages are encoded as two logically parallel streams of data.

____
MSEO - 2-bit field for detection of idle/start of message/ variable size fields.

MDO - N-bit field which carries payload of message (6-bit TCODE followed by other TCODE-dependent fields: addresses, counters, statuses etc.).
____

[arabic, start=3]
. *_Nexus spec_* permits 1-bit MSEO (being sequence of 2 bits …), but in order to reduce complexity (on both SoC and trace tool sides) this should not be utilized for RISC-V.
[arabic]
.. STS (Serial Trace Sink) and PTS (Parallel Trace Sink) chapters define how single-bit transport is handled.
. *_Nexus spec_* permits any number of MDO bits, but for simplicity RISC-V should permits ‘even’ number of MDO bits, so entire Nexus message will be always N*8 bits (i.e. N bytes) long.
[arabic]
.. Handling generic bit-sized in trace decoding software would be complex and slow.
.. Said so, permitted supported MDO sizes will be 6/14/22/30-bit + 2bit MSEO (1/2/3/4-byte).
.. Bigger MDO widths have less MSEO-related overhead, but from other hand the necessary padding (due to fact that all fields must be MDO bits-aligned) may nullify any gain.
.. Said so it is *strongly recommended* to use MSEO=2 and MDO=6 configuration. If case of wider export port (16/32-bit), several Nexus bytes (possibly from different Nexus messages will be packed together). TODO: Should we consider only perming 2+6 configuration?
. When we have 8-bit packet (MSEO+MDO) Nexus messages can be easily saved into RAM as sequence of bytes - also parallel transport (off-chip) using 8/4/2/1 is easy.
[arabic]
.. In case of 16 bit transport, two bytes will fit. Wider transport (24-bit, 32-bit) is also possible, but number of hardware tools providing such capture is limited.

