[[header]]
:company: RISC-V
:revdate:  Jan 10, 2023
:revnumber: 0.9.12
:revremark: This document is in Stable state. Assume it may change.
:url-riscv: http://riscv.org
:doctype: book
:preface-title: Preamble
:colophon:
:appendix-caption: Appendix
:title-logo-image: image:docs-resources/images/risc-v_logo.svg[pdfwidth=3.25in,align=center]
// Settings:
:experimental:
:reproducible:
:WaveDromEditorApp: wavedrom-cli
:icons: font
:lang: en
:listing-caption: Listing
:sectnums:
:sectnumlevels: 5
:toclevels: 5
:toc: left
:source-highlighter: pygments
ifdef::backend-pdf[]
:source-highlighter: coderay
endif::[]
:data-uri:
:hide-uri-scheme:
:stem: latexmath
:footnote:
:xrefstyle: short 

= RISC-V N-Trace Specification

// table of contents
toc::[]

[NOTE]
.Copyright and licensure:
====
This work is licensed under a
link:http://creativecommons.org/licenses/by/4.0/[Creative Commons Attribution 4.0 International License].

This work is Copyright 2023 by RISC-V International.
==== 

[preface]
== Document State

PDF generated on: {localdatetime}

2023/01/10: Version 0.9.12-Stable

NOTE: See https://wiki.riscv.org/display/HOME/Specification+States for explanation of specification states.

= Introduction to N-Trace and Nexus

N-Trace specification provides specification of complete, end-to-end, trace system for RISC-V cores and harts.

N-Trace is based on well established Nexus trace standard, but during development process the following key design decisions were made:

* Trace ingress port (connection between hart and trace sub-system) is identical as in ratified E-Trace specification.

* Nexus messages are kept compatible with the original Nexus specification (an appropriate subset applicable to RISC-V was selected).

** Subset was limited to program trace only, but it will be followed by Nexus compliant data and bus trace.

* Trace control layer defined in Nexus specification was message based and it would be hard to adopt it. Instead, donated by SiFive, a proven working control layer specification was adopted and extended. It assured that in the moment of N-Trace ratification most trace tool vendors will be able to provide full support with minimal changes in trace control software. This control specification was agreed to be shared with ratified E-Trace specification, so the RISC-V trace sub-system will be more unified and easier to understand and handle.

* Trace connectors defined by Nexus were debug oriented, so could not be easily used. Instead, industry standard MIPI-compliant connectors (MIPI20 and Mictor-38) which are supported by all debug and trace probes for a long time are used (with small, generic extensions). These connectors are pure extensions of connectors defined in ratified RISC-V Debug Specification.

NOTE: This specification does NOT require developers (both IP developers and trace tool developers) to become familiar with any other documentation besides PDF files provided below. These PDF files are providing links to original PDF files (Nexus Specification, SiFive Control Layer Donation, MIPI Connectors White Paper) as references.

= Specification PDFs

This document provides reference to separated documents developed together as part of RISC-V N-Trace Specification:

* https://github.com/riscv-non-isa/tg-nexus-trace/tree/master/pdfs/RISC-V-Trace-Nexus-Messages.pdf[Specification of RISC-V Nexus Trace Messages] - Defines RISC-V Nexus-based trace messages.
* https://github.com/riscv-non-isa/tg-nexus-trace/tree/master/pdfs/RISC-V-Trace-Control-Interface.pdf[Specification of RISC-V Trace Control Interface] - Defines RISC-V trace control interface.
* https://github.com/riscv-non-isa/tg-nexus-trace/tree/master/pdfs/RISC-V-Trace-Connectors.pdf[Specification of RISC-V Trace Connectors] - Defines RISC-V trace connectors (for external trace probes).

Document `Specification of RISC-V Trace Control Interface` is intended to be shared with ratified `Efficient Trace for RISC-V Specification (v2.0.0)` document.

NOTE: Currently above links reference working versions of PDFs. Once ratified, these links will point to officially ratified versions.

NOTE: Currently each PDF has a different 'working version' (`v0.9.x`). Ratified set of documents (including this document) will all have identical version numbers (`v1.0.0`).

= Useful Links

Specification was developed here:

https://github.com/riscv-non-isa/tg-nexus-trace

Reference N-Trace encoder/dumper/decoder with separated documentation and set of tests is provided here:

https://github.com/riscv-non-isa/tg-nexus-trace/tree/master/refcode/c

Mailing list for Nexus Trace TG, which developed this specification is available here:

https://lists.riscv.org/g/tech-nexus

